sudo: false

language: php

php:
    - 7.2

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - travis_retry composer install --classmap-authoritative --no-suggest --prefer-dist

script:
    - vendor/bin/phpunit

jobs:
    include:

        - stage: Code Quality
          env: CODING_STANDARDS
          script:
              - vendor/bin/phpcs -p

stages:
    - Test
    - name: Code Quality
      if: type = pull_request

cache:
    directories:
        - $HOME/.composer/cache/files
