sudo: false

language: php

php: 7.2

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - travis_retry composer install --classmap-authoritative --no-suggest --prefer-dist

jobs:
    include:

        - stage: Test
          name: Tests
          script:
          - vendor/bin/phpunit

        - stage: Code Quality
          name: Coding standards
          script:
              - vendor/bin/phpcs -p

stages:
    - Test
    - name: Code Quality
      if: type = pull_request

cache:
    directories:
        - $HOME/.composer/cache/files

if: |
    branch = master OR \
    branch =~ /^(?:[0-9]|[1-9][0-9]*)\.(?:[0-9]|[1-9][0-9]*)$/ OR \
    tag IS present OR \
    type = pull_request
