#%RAML 1.0 Library
usage: Common Libero constructs.

resourceTypes:
    base:
        get?: &common
    item:
        type: base
        usage: This resource type should be used for any single item.
        get?:
            responses:
                404:
                    description: |
                        <<resource>> is not found.
                    body:
                        application/problem+xml:
                          type: !include data/rfc7807.rng
                          example: !include samples/errors/not-found.xml
                410:
                    description: |
                        <<resource>> has been removed.
                    body:
                        application/problem+xml:
                            type: !include data/rfc7807.rng
                            example: !include samples/errors/removed.xml

traits:
    hasLanguage:
        headers:
            Accept-Language:
                required: false
                type: string
                default: '*'
                examples:
                    any:
                        displayName: Any language
                        value: '*'
                    one:
                        displayName: Specific language
                        value: en
                    many:
                        displayName: Multiple language preferences
                        value: fr-CH, fr;q=0.9, en-GB;q=0.8, en;q=0.7, de;q=0.3, *;q=0.1
